server/sell-script-backend/backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_reset_confirm, password_change
from django.conf.urls.i18n import i18n_patterns

from django.contrib.sitemaps.views import sitemap
from django.core.urlresolvers import reverse
from django.contrib.sitemaps import Sitemap
from django.views.generic import RedirectView, TemplateView
from django.contrib.staticfiles.templatetags.staticfiles import static

from clients.views import do_login
from clients.forms import SaleScriptPasswordChangeForm
from common.views import MultilingualTemplateView, current_user


class ViewSitemap(Sitemap):
    """Reverse 'static' views for XML sitemap."""

    def items(self):
        # Return list of url names for views to include in sitemap
        return ['main', 'faq']

    def location(self, item):
        return reverse(item)

    i18n = True


sitemaps = {'views': ViewSitemap}


urlpatterns = [
    #SEO
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt'), name='robots'),

    url(r'^sitemap\.xml$', TemplateView.as_view(
        template_name='sitemap.xml'), name='sitemap'),
    #

    url(r'^admin/', admin.site.urls),
    url(r'^api/current_user$', current_user),
    url(r'^api/', include('scripts.api_urls')),
    url('', include('social.apps.django_app.urls', namespace='social'))
]

urlpatterns += i18n_patterns(
    url(r'^client/', include('clients.urls')),

    #Redefine password reset confirm
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        do_login(password_reset_confirm), name='password_reset_confirm',
        kwargs={'post_reset_redirect': 'clients:dashboard'}),  #

    #Redefine password change
    url(r'^password_change/$', password_change, name='password_change',
        kwargs={'password_change_form': SaleScriptPasswordChangeForm}),

    url(r'^', include('django.contrib.auth.urls')),

    url(r'^scripts/', include('scripts.urls')),

    url(r'^$', MultilingualTemplateView.as_view(
        template_name='main.html',
        multilang_template='main.{LANGUAGE_CODE}.html'), name="main"),

    url(r'^faq$', MultilingualTemplateView.as_view(
        template_name='faq.html',
        multilang_template='faq.{LANGUAGE_CODE}.html'), name="faq"),

    url(r'^termsofuse$', RedirectView.as_view(
        url=static('salescript_toe_ru.pdf')), name='toe'),

    url(r'^confidential$', RedirectView.as_view(
        url=static('salescript_confidential_ru.pdf')), name='confidential'),

)

server/sell-script-backend/clients/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy

from .views import (DashboardView, ProfileView, ClientRegistrationView)

app_name = 'clients'
urlpatterns = [
    url(r'^register', ClientRegistrationView.as_view(
            success_url=reverse_lazy('clients:dashboard')),
        name='register'),

    url(r'^dashboard', DashboardView.as_view(),
        name='dashboard'),

    url(r'^profile', ProfileView.as_view(),
        name='profile'),
]

server/sell-script-backend/common/models.py
from django.db import models

# Create your models here.

server/sell-script-backend/common/views.py
from django.views.generic import TemplateView

from rest_framework.decorators import api_view
from rest_framework.response import Response

from scripts.models import Script


class MultilingualTemplateView(TemplateView):
    multilang_template = None

    def get_template_names(self):
        templates = super().get_template_names()
        if (self.request.LANGUAGE_CODE is not None and
                self.multilang_template is not None):
            templates.insert(0, self.multilang_template.format(
                LANGUAGE_CODE=self.request.LANGUAGE_CODE.lower()))
        return templates


@api_view(['GET'])
def current_user(request):
    user = request.user
    return Response({
        'username': user.username,
        'id': user.pk,
        'email': user.email,
        'isSuperuser': user.is_superuser,
        'ownScripts':  {
            int(el['id']): el
            for el in Script.objects.allowed_to(user)
                                    .filter(has_perm_own=True)
                                    .values('id', 'title')
        }
    })

server/sell-script-backend/common/templates/faq.en.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block css-layout %}
    <link href="{% static "css/main/page.css" %}"
          rel="stylesheet">
{% endblock %}
{% block brand %}{% trans "Sales scripts. Free designer - SaleScript.gift" %}{% endblock %}
{% block title-subject %}{% trans "Frequently Asked Questions"|capfirst %}{% endblock %}
{% block main %}
    <main role="main">
        <h2>{% trans "F.A.Q."|capfirst %}</h2>
        <section>
            <h3>How to add questions to the Scenario?</h3>
            <p>First, you have to add the first reply of your operator to the
                conversation scenario. Usually, the first question contains
                greeting and representation of employee. To do this, click on "Add a question".
                Your question in rectangular shaped block will appear.
            </p>
        </section>
        <section>
            <h3>How to add answer option to the Script?</h3>
            <p>Select needed question of your operator, click "Add option" button,
                and add the answers. The "Add option" button is displayed if one
                of the questions is selected.
            </p>
        </section>
        <section>
            <h3>Why only the manager asks questions, and the client only responds?</h3>
            <p>It is formal. But in general, is not it more productive to maintain
                initiative of manager and ask questions?
            </p>
        </section>
        <section>
            <h3>How to edit the contents of questions and answers blocks?</h3>
            <p> Select the desired block with the mouse - it becomes highlighted
                in blue. While it is highlighted, you can edit the content in the
                right column - in the "Node Properties" box.
            </p>
        </section>
        <section>
            <h3> How can link the questions and the answers blocks?</h3>
            <p>Choose a block with the client's answer, and you will be able to
                connect it with one of the Operator's replies by the clicking
                on the "Link" button, and then, selecting an appropriate Question
                block. For your convenience, the questions blocks at this point
                are highlighted in green. Blocks and connection lines of the
                Scenario aligned automatically.
            </p>
        </section>
        <section>
            <h3>How to move into the editor field in the Script Editor?</h3>
            <p>Use the horizontal and vertical scroll bars and the mouse wheel to
                scroll the editor field. This is important when you are working with the
                large-scale scripts. In addition, use the Zoom control in the top right
                corner of the Editor.
            </p>
        </section>
        <section>
            <h3>Why are blocks "Start" and "Success" and how to use them?</h3>
            <p>These blocks are required for the script engine for the editor and
                viewer to know the beginning and the end - please connect Client's response,
                which is the purpose of your script to the "Success" block, which was
                originally created by the Editor.
                This will create a loop in the script, and you will be automatically
                returned to the start point of the script to begin with another
                customer after achieving target of the conversation with the
                current customer in the View mode.
            </p>
        </section>
        <section>
            <h3>How to save a script that I've created</h3>
            <p>Fill in the name of the script in the Editor, and click the "Save".
            </p>
        </section>
        <section>
            <h3>Tell me, is it possible to give access to my script to another users?</h3>
            <p>Yes, you can give the script access to other people, see "Rights".
                Just send them an invitation by e-mail, and set permissions.
                When they enter the SaleScript, passing the link in the e-mail,
                they will see the script in the Dashboard.
            </p>
        </section>
        <section>
            <h3>Tell me, is it possible to export the scenario, and use it offline?
                What about scripts import?</h3>
            <p>We don't have these opportunities yet. Our users voted for CRM in
                last polling. We implement CRM, and then, we will suggest import/export
                in the next voting to find out what things are most important to be done.
            </p>
        </section>
    </main>
{% endblock %}

server/sell-script-backend/common/templates/faq.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block css-layout %}
    <link href="{% static "css/main/page.css" %}"
          rel="stylesheet">
{% endblock %}
{% block brand %}{% trans "Sales scripts. Free designer - SaleScript.gift" %}{% endblock %}
{% block title-subject %}{% trans "Frequently Asked Questions"|capfirst %}{% endblock %}
{% block main %}
    <main role="main">
        <h2>{% trans "F.A.Q."|capfirst %}</h2>
        <section>
            <h3>Как добавлять вопросы к скрипту?</h3>
            <p>Первым делом необходимо добавить в сценарий разговора первую реплику
                вашего оператора. Обычно, в первый вопрос размещают приветствие и
                представление сотрудника. Для этого, нажмите «Добавить вопрос».
                У вас появится блок вопроса прямоугольной формы.
            </p>
        </section>
        <section>
            <h3>Как добавлять ответы клиента к скрипту?</h3>
            <p>Выделите нужный вопрос вашего оператора и нажмите кнопку «Добавить
                вариант ответа» и добавляйте варианты. Кнопка "Добавить вариант
                ответа" появляется при выделении какого-либо из вопросов мышью.
            </p>
        </section>
        <section>
            <h3>Почему менеджер задает вопросы, а клиент только отвечает?</h3>
            <p>Это условно. Но вообще, разве не продуктивнее менеджеру удерживать
                инициативу и для этого задавать вопросы?
            </p>
        </section>
        <section>
            <h3>Как редактировать содержимое блоков вопросов и ответов?</h3>
            <p>Выделите необходимый блок мышью — он станет подсвечен голубым.
                Пока он выделен, вы можете редактировать его содержание в правой
                колонке — в блоке «Свойства элемента».
            </p>
        </section>
        <section>
            <h3>Как связывать между собой блоки вопросов и ответов?</h3>
            <p>Выделив блок с ответом Клиента вы также получаете возможность
                связать его с каким-либо из вопросов Оператора, нажимая кнопку
                «Связать», а затем нажав на нужный вопрос. Для удобства, блоки
                вопросов в этот момент подсвечиваются зеленым цветом. Расположение
                блоков и связывающие линии выравниваются автоматически.
            </p>
        </section>
        <section>
            <h3>Как перемещаться по полю ввода скрипта в редакторе?</h3>
            <p>Вы можете перемещаться по полю ввода скрипта при помощи
                горизонтального и вертикального ползунков, а также вращая колесо
                мыши — очень важно при создании больших скриптов. Также можно
                увеличивать и уменьшать масштаб отображения скрипта используя
                ползунок «Масштаб» в правом верхнем углу.
            </p>
        </section>
        <section>
            <h3>Зачем нужны блоки «Начало» и «Успех» и как ими пользоваться?</h3>
            <p> Это программная необходимость, чтобы редактор и просмотрщик знали
                где начало, а где конец — обязательно соедините ответы Клиента,
                связанные с достижением цели вашего скрипта с пунктом «Успех»,
                который был введен автоматически с самого начала. Это замкнет
                скрипт и вернет его к началу, чтобы вы могли сразу же включиться
                в работу со следующим клиентом, когда будете находиться в режиме
                просмотра.
            </p>
        </section>
        <section>
            <h3>Как сохранить скрипт, который я набрал?</h3>
            <p>В редакторе дайте скрипту имя и описание и обязательно нажмите
                кнопку «Сохранить».
            </p>
        </section>
        <section>
            <h3>Скажите, есть возможность, чтобы мой скрипт мог использовать
                другой пользователь?</h3>
            <p>Да, вы можете предоставить к скрипту доступ другим людям в разделе
                "права". Просто вышлите им на почту приглашения и назначьте уровень
                доступа. Когда они зарегистрируются в системе, пройдя по ссылке
                из письма, у них на рабочем столе будет ваш скрипт.
            </p>
        </section>
        <section>
            <h3>Скажите, у вас в системе есть возможность экспорта скрипта, чтобы
                он был доступен оффлайн? А импорта скриптов в систему?</h3>
            <p>Пока такой возможности нет. В прошлом голосовании пользователи
                проголосовали за создание CRM, а не за экспорт/импорт скриптов.
                Когда сделаем CRM - предложим следующее голосование и снова можно
                будет выбрать то, что наиболее актуально и ценно сделать.
            </p>
        </section>
        <section>
            <h3>Когда скрипт разрастается - становится неудобно искать по всему экрану нужную фразу, можно ли как-то сделать по нему поиск?</h3>
            <p>Специальной функции поиска нет, но вы можете нажать стандартную комбинацию клавиш CTRL+F и в появившейся форме вводить нужные слова.
            </p>
        </section>
       <section>
       <h3>Не получается восстановить пароль учетной записи. Я регистрировался через учетную запись социальной сети.</h3>
       <p>Попробуйте продолжать входить через эту же учетную запись. Назначение и восстановление паролей для них не требуется.</p>
       </section>
       <section>
       <h3>Q: Есть ли возможность в вашей программе дублировать сценарии? То есть я хочу скопировать сделанный сценарий и его редактировать, а не создавать заново.</h3>
       <p>A: Копировать сценарий можно! Для этого, сначала выберите сценарий, нужный вам для копирования в редакторе, затем там же выберите пустое поле названия, назовите иначе и сохраните. У вас будет два одинаковых скрипта под разными названиями. Далее модифицируйте как хотите.</p>
       </section>
    </main>
{% endblock %}

server/sell-script-backend/common/templates/fb_groups.inc.html
<noindex>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=569033233291314";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-page" data-href="https://www.facebook.com/salescript/" data-tabs="timeline, messages" data-small-header="true" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="false"><blockquote cite="https://www.facebook.com/salescript/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/salescript/">SaleScript.Gift</a></blockquote></div>
</noindex>

server/sell-script-backend/common/templates/main.en.html
{% extends 'base.html' %}
{% load i18n social_login %}
{% load staticfiles %}

{% block css-layout %}
    <link href="{% static "css/main/page.css" %}"
          rel="stylesheet">
{% endblock %}
{% block brand %}{% trans "Sales scripts. Free designer - SaleScript.gift" %}{% endblock %}
{% block title %}Sales script for free. SaleScript.Gift designer{% endblock %}
{% block head-description %}Sales scripts for free, create your own conversation scenario.{% endblock %}
{% block content %}
    <div class="mainpage">
        <div class="slide about">

            <div class="row">

                <div class="picture-block">
                    <iframe width="427" height="240" src="https://www.youtube.com/embed/dRt4vuqIw1g?rel=0" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="text-block">

                    <h1>Free sales scripts generator</h1>

                    <p>Welcome to the open beta testing of sales scripts constructor
                        SaleScript.gift.
                        Important: see the video manual on this page before you
                        start work.</p>
                    <p>
                        The good news: sales scripts generator will remain free
                        forever. With your help, we successfully improve the functionality,
                        and will soon begin work on expanding the capacity of our project,
                        to create from it a full-fledged cold sales lead generation
                        machine and even more.
                        However, this is only the beginning. We still have a lot of interesting ideas
                        which we hope to bring to life.</p>

                    <p>To do this we need your help. Any comments about bugs and
                        shortcomings of the system, help with proper localization,
                        you can always send us through our Facebook page.
                        We'll be very grateful. You can also support the project
                        financially on a purely voluntary basis.</p>

                </div>
            </div>
        </div>
        <div class="slide scripts">
          <div class="row">
            <div class="picture-block">
                {# Fb groups #}
                {% include "fb_groups.inc.html" %}
                {# End Fb groups #}
            </div>
            <h2>What is conversations (sales) scripts</h2>
            <p>Scripts of conversations, often called sales scripts - a detailed
                scenario of conversation on the phone. It significantly reduces
                the risk of losing a client, both potential and existing related
                management incompetence, stress factors, and helps to learn to a
                high standard talking on the phone a new member of your team,
                reducing the training period. By implementing a scripts of calls
                to your business, you can after a short period of internship
                (1-2 weeks) to set the salaries of employees, according to its
                real value for the company and it certainly will not be offended,
                because there will be quite confident. Depending on the purpose
                for which designed call script, they can be used for:</p>
            <ul>
                <li>Cold calls to organizations and to individuals</li>
                <li>Handling incoming calls</li>
                <li>Customer Service</li>
                <li>Gathering information about competitors</li>
                <li>Re-sale calls</li>
                <li>Poll of satisfaction on the cooperation</li>
            </ul>
            <p>And not limited to these. After all, you can virtually eliminate
                the factor of chance and incompetence of the employees in any
                communication with the client. Employees on the phone is the face
                of your company, in fact, they often give the impression of it</p>
             </div>
        </div>
        <div class="slide scripts-how">
            <h2>What sales script should include</h2>
            <p>Depending on the purpose, the script composition may be different.
                The main thing that you need to achieve - is the goal of a particular
                scenario. In one case, it may be a sale, in another - the removal
                of emotional intensity (support staff). You have to determine for
                themselves the link from which you will get the maximum conversion
                to sale, the solution customer problems and so on.</p>

            <p>The main sections of high-quality sales script may include:</p>

            <ul>
                <li>The conversation with the secretary, identify the person
                    making the decision (DM) and getting in touch with him</li>
                <li>Detection of the needs of decision-makers in your product/service</li>
                <li>Product Presentation</li>
                <li>Work with objections</li>
                <li>Closing oo the target of the script</li>
                <li>Additional sale</li>
            </ul>
            <p>You should monitor your managers, listen to the recording of calls,
                create checklists on the main points for the best results. By
                implementing sales scripts you can dramatically improve your sales.
                Who wants to get rich?</p>
        </div>
        <div class="slide getready">
            <p>Log on and make your first sales script! Start your way to success
                absolutely free without any limitations.</p>
            <a href="{% url 'clients:register' %}?next={% url 'clients:dashboard' %}"
               class="btn btn-success">Register</a> or use social networks login: {% social_login %}
            {#Sharebuttons#}
            {% include "share_buttons.inc.html" %}
            {#End Sharebuttons#}
        </div>
    </div>
{% endblock %}

server/sell-script-backend/common/templates/main.html
{% extends 'base.html' %}
{% load i18n social_login %}
{% load staticfiles %}

{% block css-layout %}
    <link href="{% static "css/main/page.css" %}"
          rel="stylesheet">
{% endblock %}

{% block title %}Скрипты продаж бесплатно. Генератор SaleScript.Gift{% endblock %}
{% block head-description %}Скрипты продаж бесплатно навсегда, составьте свой сценарий разговора.{% endblock %}
{% block brand %}{% trans "Sales scripts. Free designer - SaleScript.gift" %}{% endblock %}
{% block content %}
    <div class="main">
        <div class="slide about">

            <div class="row">

                <div class="picture-block">
                    <iframe width="427" height="240" src="https://www.youtube.com/embed/dRt4vuqIw1g?rel=0" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="text-block">

                    <h1>Бесплатный генератор скриптов продаж</h1>

                    <p>Добро пожаловать на открытое бета-тестирование генератора
                        скриптов продаж
                        SaleScript.gift. Важно: посмотрите видео на этой странице, прежде чем начнете работу.</p>
                    <p>
                        Хорошая новость: генератор скриптов продаж останется
                        бесплатным навсегда. С
                        вашей помощью, мы успешно улучшаем этот функционал, а скоро
                        начнем работать и
                        над расширением возможностей всей системы, чтобы создать
                        из нее полноценную
                        машину лидогенерации в холодных продажах и не только.
                        Однако, это только
                        начало. У нас есть еще очень много интересных мыслей,
                        которые мы надеемся
                        воплотить в жизнь.</p>

                    <p>Для этого нам требуется ваша помощь. Любые замечания об
                        ошибках и недостатках
                        системы вы всегда можете отправить нам через
                        нашу страницу VK. Мы будем
                        вам очень благодарны. Вы также можете поддержать проект
                        финансово на сугубо
                        добровольной основе.</p>

                </div>
            </div>
        </div>
        <div class="slide scripts">
           <div class="row">
            <div class="picture-block">
                {# Vk groups #}
                {% include "vk_groups.inc.html" %}
                {# End Vk groups #}
            </div>
            <div class="text-block">
            <h2>Что такое скрипты разговоров (продаж)</h2>
            <p>Скрипты разговоров, чаще называемые скриптами продаж - это
                подробный сценарий
                разговора по телефону. Он значительно снижает риски потерять
                клиента, как
                потенциального, так и уже имеющегося, связанные с
                некомпетентностью
                менеджера, стрессовыми факторами, а также помогает научиться
                высокому
                стандарту разговора по телефону новому члену вашей команды,
                сокращая период
                обучения. Внедрив скрипты звонков на своем предприятии, вы
                сможете после
                небольшого периода стажировки (1-2 недели) установить зарплату
                сотрудника, в
                зависимости от его реальной ценности для компании и он наверняка
                не
                обидится, потому что уже будет достаточно уверен в себе. В
                зависимости от
                того, для чего разработан скрипт разговора, их можно применять
                для:</p>
            <ul>
                <li>Холодные звонки в организации и к частным лицам</li>
                <li>Обработка входящих звонков</li>
                <li>Служба поддержки клиентов</li>
                <li>Сбор информации о конкурентах</li>
                <li>Повторная продажа по телефону</li>
                <li>Опрос об удовлетворенности сотрудничеством</li>
                <li>Общении при взыскании задолженности с клиента (коллекторская служба)</li>
            </ul>
            <p>И даже не ограничиваясь этим. Ведь вы можете практически
                полностью исключить
                фактор случайности и некомпетентности сотрудников при любом
                общении с
                клиентом. А сотрудники на телефоне - это лицо вашей компании, по
                сути,
                именно они часто и создают впечатление о ней.</p>
                </div>
           </div>
        </div>
        <div class="slide scripts-how">
        <div class="row">
         <div class="picture-block">
         <noindex>
         <iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/quickpay/shop-widget?account=410011260096230&quickpay=shop&payment-type-choice=on&mobile-payment-type-choice=on&writer=seller&targets=%D0%9F%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82%D1%8C+%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82&targets-hint=&default-sum=100&button-text=04&comment=on&hint=&successURL=https%3A%2F%2Fsalescript.gift%2Fru%2F" width="435" height="274"></iframe>
         </noindex>
         </div>
            <div class="text-block">
            <h2>Что должен включать в себя скрипт продаж</h2>
            <p>В зависимости от поставленных целей, состав скрипта может быть
                различным.
                Главное, что необходимо достичь - это цель конкретного сценария.
                В одном
                случае, это может быть продажа, в другом - снятие эмоционального
                накала
                (служба поддержки), в третьем, как например в оконной компании -
                продажа не
                окон, а лишь вызова замерщика. Вы сами должны определить для
                себя то звено,
                с которого получите максимальную конверсию в продажи, решение
                проблем
                клиента и т. д.</p>

            <p>Как бы то ни было, основные разделы качественного скрипта продаж
                могут
                включать:</p>

            <ul>
                <li>Разговор с секретарем, выявление лица принимающего решение
                    (ЛПР) и
                    получение контакта с ним
                </li>
                <li>Выявление у ЛПР потребности в Вашем продукте/услуге</li>
                <li>Презентация продукта/услуги</li>
                <li>Работа с возражениями</li>
                <li>Закрытие на цель скрипта</li>
                <li>Дополнительная продажа</li>
            </ul>
            <p>Вам стоит контролировать своих менеджеров, прослушивать записи
                звонков,
                создать чеклисты по основным моментам. Считается, что внедрение
                скриптов
                разговоров на предприятии - это мировой стандарт качества
                обслуживания
                клиентов, и это пожалуй, действительно так. Внедрив скрипты
                продаж - вы
                выведете свою компанию на средний мировой уровень, а если
                постараетесь, то
                даже выше среднего уровня. Но в любом случае, вы можете
                значительно улучшить
                свои продажи. Кто хочет разбогатеть?</p>
        </div>
        </div>
        </div>
        <div class="slide getready">
            <p>Зарегистрируйтесь в системе и создайте свой первый скрипт
                разговора! Начните
                свой путь к успеху абсолютно бесплатно.</p>
            <a href="{% url 'clients:register' %}?next={% url 'clients:dashboard' %}"
               class="btn btn-success">Регистрация</a> либо воспользуйтесь входом через социальные сети: {% social_login %}
            {#Sharebuttons#}
            {% include "share_buttons.inc.html" %}
            {#End Sharebuttons#}
        </div>
        <script type="text/javascript" src="//vk.com/js/api/openapi.js?136"></script>

<!-- VK Message Widget -->
<div id="vk_community_messages"></div>
<script type="text/javascript">
VK.Widgets.CommunityMessages("vk_community_messages", 115083644, {});
</script>
    </div>
{% endblock %}

server/sell-script-backend/common/templates/navbar_user.html
{% load i18n %}
{% if user.is_active %}
    <li class="current-user">
        <a href="{% url 'clients:profile' %}">
            <span class="glyphicon glyphicon-user"></span>{{ user }}
        </a>
    </li>
    <li>
        <a href="{% url 'logout' %}?next={% url 'main' %}">
            {% trans "sign out"|capfirst %}
        </a>
    </li>
{% else %}
    <li class="current-user">
        <a href="{% url 'login' %}?next={% url 'clients:dashboard' %}">
            <span class="glyphicon glyphicon-user"></span>
            {% trans "sign in"|capfirst %}
        </a>
    </li>
    <li>
        <a href="{% url 'clients:register' %}?next={% url 'clients:dashboard' %}">{% trans "register"|capfirst %}</a>
    </li>
{% endif %}

server/sell-script-backend/common/templates/social_login.html
{% load backend_utils %}
{% for sublist in available_backends|social_backends %}
    {% for name, backend in sublist %}
        <a class="btn btn-default" id="{{ name }}-button" name="{{ backend|backend_class }}" href="{% url "social:begin" backend=name %}">
            <i class="fa fa-{{ name|icon_name }}"></i>
            {{ backend|backend_name }}
        </a>
    {% endfor %}
{% endfor %}

server/sell-script-backend/common/templates/vk_groups.inc.html
<noindex>
<script type="text/javascript" src="//vk.com/js/api/openapi.js?136"></script> 

<!— VK Widget —> 
<div id="vk_groups"></div> 
<script type="text/javascript"> 
VK.Widgets.Group("vk_groups", {mode: 4, wide: 1, width: "220", height: "400"}, 115083644); 
</script>
</noindex>