server/sell-script-backend/backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_reset_confirm, password_change
from django.conf.urls.i18n import i18n_patterns

from django.contrib.sitemaps.views import sitemap
from django.core.urlresolvers import reverse
from django.contrib.sitemaps import Sitemap
from django.views.generic import RedirectView, TemplateView
from django.contrib.staticfiles.templatetags.staticfiles import static

from clients.views import do_login
from clients.forms import SaleScriptPasswordChangeForm
from common.views import MultilingualTemplateView, current_user


class ViewSitemap(Sitemap):
    """Reverse 'static' views for XML sitemap."""

    def items(self):
        # Return list of url names for views to include in sitemap
        return ['main', 'faq']

    def location(self, item):
        return reverse(item)

    i18n = True


sitemaps = {'views': ViewSitemap}


urlpatterns = [
    #SEO
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt'), name='robots'),

    url(r'^sitemap\.xml$', TemplateView.as_view(
        template_name='sitemap.xml'), name='sitemap'),
    #

    url(r'^admin/', admin.site.urls),
    url(r'^api/current_user$', current_user),
    url(r'^api/', include('scripts.api_urls')),
    url('', include('social.apps.django_app.urls', namespace='social'))
]

urlpatterns += i18n_patterns(
    url(r'^client/', include('clients.urls')),

    #Redefine password reset confirm
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        do_login(password_reset_confirm), name='password_reset_confirm',
        kwargs={'post_reset_redirect': 'clients:dashboard'}),  #

    #Redefine password change
    url(r'^password_change/$', password_change, name='password_change',
        kwargs={'password_change_form': SaleScriptPasswordChangeForm}),

    url(r'^', include('django.contrib.auth.urls')),

    url(r'^scripts/', include('scripts.urls')),

    url(r'^$', MultilingualTemplateView.as_view(
        template_name='main.html',
        multilang_template='main.{LANGUAGE_CODE}.html'), name="main"),

    url(r'^faq$', MultilingualTemplateView.as_view(
        template_name='faq.html',
        multilang_template='faq.{LANGUAGE_CODE}.html'), name="faq"),

    url(r'^termsofuse$', RedirectView.as_view(
        url=static('salescript_toe_ru.pdf')), name='toe'),

    url(r'^confidential$', RedirectView.as_view(
        url=static('salescript_confidential_ru.pdf')), name='confidential'),

)

server/sell-script-backend/scripts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import ExportScriptsView, ImportScriptsView

app_name = 'scripts'
urlpatterns = [
    url(r'^editor', TemplateView.as_view(template_name='scripts/editor.html'),
        name='editor'),
    url(r'^viewer', TemplateView.as_view(template_name='scripts/viewer.html'),
        name='viewer'),
    url(r'^preferences', TemplateView.as_view(template_name='scripts/preferences.html'),
        name='preferences'),
    url(r'^stats', TemplateView.as_view(template_name='scripts/stats-summary.html'),
        name='stats-all'),
    url(r'^download', ExportScriptsView.as_view(),
        name='download'),
    url(r'^migrate', ImportScriptsView.as_view(),
        name='migrate'),
]

server/sell-script-backend/scripts/models.py
from django.db import models
from django.db.models import Case, When, BooleanField, Value
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


class ScriptQuerySet(models.QuerySet):
    def allowed_to(self, user):
        def perm_lookup_expr(*perms):
            return Case(When(
                pk__in=ScriptPermission.objects.filter(
                    user=user,
                    permission__in=ScriptPermission.perms(*perms))
                                                   .values('script__id'),
                then=Value(True)),
                    default=Value(False),
                    output_field=BooleanField())
        return (self
            .filter(pk__in=ScriptPermission.objects
                .filter(user=user)
                .values("script_id"))
            .annotate(
                has_perm_own=perm_lookup_expr('script_own'),
                has_perm_execute=perm_lookup_expr('script_own', 'script_execute'),
                has_perm_change=perm_lookup_expr('script_own', 'script_change'),
                has_perm_view=perm_lookup_expr('script_own', 'script_change',
                                               'script_execute', 'script_view'))
            .filter(has_perm_view=True))


class Script(models.Model):
    """
    Scenario model
    """
    objects = ScriptQuerySet.as_manager()
    title = models.CharField(verbose_name=_('title'), max_length=250)
    text = models.TextField()
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                               verbose_name=_('author'),
                               related_name='own_scripts')
    description = models.TextField(verbose_name=_('description'),
                                   blank=True, null=False)
    created = models.DateTimeField(verbose_name=_('creation date'),
                                   auto_now_add=True, editable=False)

    def __str__(self):
        return '{0} - {1}'.format(self.title, self.author)

    class Meta:
        permissions = (
            ('script_own', 'Script owner (r,w,x)'),
            ('script_execute', 'Run script in viewer with stats'),
            ('script_change', 'Save script in editor'),
            ('script_view', 'Run script in viewer w/o stats')
        )
        ordering = ('-created',)


class ScriptPermission(models.Model):
    """
    Script permission
    """
    script = models.ForeignKey(to=Script, related_name='permissions',
                               null=False, blank=False)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, null=False,
                             blank=False)
    permission = models.ForeignKey(
        to='auth.Permission',
        null=False,
        blank=False,
        limit_choices_to=lambda: ScriptPermission.get_permissions_filter())

    @classmethod
    def get_permissions_filter(cls):
        return {'codename__in': (p[0] for p in Script._meta.permissions),
                'content_type': ContentType.objects.get_for_model(Script)}

    @classmethod
    def perms(cls, *args):
        return Permission.objects.filter(
            content_type=ContentType.objects.get_for_model(Script),
            codename__in=args)

    @classmethod
    def view_perms(cls):
        return cls.perms('script_own', 'script_execute', 'script_change',
                         'script_view')

    @classmethod
    def user_has_update_perm(cls, user, obj):
        perms = cls.perms('script_own', 'script_change')
        return cls.objects.filter(user=user, script=obj,
                                  permission__in=perms).exists()

    @classmethod
    def user_has_delete_perm(cls, user, obj):
        perms = cls.perms('script_own')
        return cls.objects.filter(user=user, script=obj,
                                  permission__in=perms).exists()

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.script.title, self.user,
                                        self.permission)

    class Meta:
        unique_together = ('script', 'user', 'permission')


@receiver(post_save, sender=Script)
def script_post_save(sender, instance: Script,
                     created: bool, raw: bool, using,
                     *args, **kwargs):
    if created and not raw:
        ScriptPermission.objects.using(using).create(
            script=instance,
            user=instance.author,
            permission=Permission.objects.get_by_natural_key(
                'script_own',
                'scripts',
                'script'))

server/sell-script-backend/scripts/views.py
import json

from django.core.files import File
from django.http import HttpResponse
from django.views.generic import View, FormView
from django.views.decorators.cache import never_cache
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import viewsets
from rest_framework.permissions import BasePermission, SAFE_METHODS
from rest_framework import status
from rest_framework.response import Response

from .models import Script, ScriptPermission
from .serializers import ScriptSerializer, ScriptPermissionSerializer


class ScriptPerms(BasePermission):
    def has_permission(self, request, view):
        return request.user and request.user.is_authenticated()

    def has_object_permission(self, request, view, obj):
        if request.method == 'PUT':
            return obj.has_perm_change
        if request.method == 'DELETE':
            return True
        return request.method in SAFE_METHODS


class ScriptViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows scripts to be viewed or edited.
    """
    queryset = Script.objects.all()
    serializer_class = ScriptSerializer
    permission_classes = [ScriptPerms]

    def get_queryset(self):
        return super().get_queryset().allowed_to(self.request.user)

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        ScriptPermission.objects.filter(
            script=instance, user=request.user).delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ScriptPermissionPerms(BasePermission):
    def has_permission(self, request, view):
        if view.script is None:
            view.set_script_from_request()
        return request.user and view.script.has_perm_change

    def has_object_permission(self, request, view, obj: ScriptPermission):
        if request.method not in SAFE_METHODS:
            return obj.user != obj.script.author
        return True



class ScriptPermissionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows concrete script's permissions to be viewed or edited.
    """
    queryset = ScriptPermission.objects.all()
    serializer_class = ScriptPermissionSerializer
    script = None
    permission_classes = [ScriptPermissionPerms]

    def set_script_from_request(self):
        self.script = (
            Script.objects.allowed_to(self.request.user)
                .prefetch_related('permissions')
                .get(pk=self.kwargs['script_pk'], has_perm_own=True))

    def get_queryset(self):
        self.set_script_from_request()
        return self.script.permissions.get_queryset().order_by("user__username")

    def get_serializer_context(self):
        if self.script is None:
            self.set_script_from_request()
        return super().get_serializer_context()


class ExportScriptsView(LoginRequiredMixin, View):
    @never_cache
    def get(self, request, *args, **kwargs):
        vals = {'scripts': list(Script.objects.allowed_to(self.request.user).values(
            'title', 'text', 'description'))}
        for obj in vals['scripts']:
            obj['text'] = json.loads(obj['text'])
        response = HttpResponse(json.dumps(vals, ensure_ascii=False, indent=2),
                                content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="scripts.json"'
        return response


class ImportForm(forms.Form):
    upload = forms.FileField(label=_("File for upload"))
    delete_existed = forms.BooleanField(
        label=_("Remove existed scripts before loading data"),
        required=False
    )


class ImportScriptsView(LoginRequiredMixin, FormView):
    template_name = 'scripts/migrate.html'
    form_class = ImportForm
    success_url = '/'

    def create_scripts(self, data):
        for script in data['scripts']:
            Script.objects.create(
                title=script['title'],
                text=json.dumps(script['text']),
                description=script['description'],
                author=self.request.user
            )

    def clear_data(self):
        Script.objects.filter(author=self.request.user).delete()
        ScriptPermission.objects.filter(user=self.request.user).delete()

    def form_valid(self, form):
        upfile = self.request.FILES['upload']
        name = None
        if hasattr(upfile, 'temporary_file_path'):
            name = upfile.temporary_file_path()
            upfile = None
        with File(upfile, name=name) as file:
            if name:
                file.open(mode='rb')
            if form.cleaned_data['delete_existed']:
                self.clear_data()
            values = json.loads(file.read().decode('utf-8'))
            self.create_scripts(values)
        messages.add_message(self.request, messages.INFO, _('Your scripts has been imported'))
        return super().form_valid(form)

server/sell-script-backend/scripts/templates/scripts/editor.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block append-head %}
{% compress css %}
<link href="{% static "css/editor.css" %}" rel="stylesheet">
{% endcompress %}
{% endblock %}
{% block title-subject %}{% trans "Editor" %}{% endblock %}
{% block main %}
    <h1>Loading the editor..</h1>
{% endblock %}
{% block append-body %}
    {% compress js %}
    {% include "scripts/scripts.inc.html" %}
    <script>
        $(function(){App().renderEditor('.main')});
    </script>
    {% endcompress %}
{% endblock %}

server/sell-script-backend/scripts/templates/scripts/migrate.html
{% extends 'base.html' %}
{% load i18n bootstrap3 %}
{% block title-subject %}Export/Import Profile{% endblock %}
{% block main %}
  <div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#export" aria-controls="export" role="tab"
           data-toggle="tab">{% trans 'export data'|capfirst %}</a>
      </li>
      <li role="presentation">
        <a href="#import" aria-controls="import" role="tab"
           data-toggle="tab">{% trans 'import data'|capfirst %}</a>
      </li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="export">
        <div class="row">
          <div class="col-sm-12">
            <a class="btn btn-lg btn-success"
               href="{% url 'scripts:download' %}">{% trans "Download Users's data" %}</a>
          </div>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane" id="import">
        <div class="row">
          <div class="col-sm-12">
            <form enctype="multipart/form-data" class="col-md-8 form" action="{% url 'scripts:migrate' %}" role="form" method="post">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% buttons %}
                <button type="submit" class="btn btn-primary">
                  {% trans "Import" %}
                </button>
              {% endbuttons %}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

server/sell-script-backend/scripts/templates/scripts/preferences.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block title-subject %}{% trans "Team" %}{% endblock %}
{% block append-head %}
{% compress css %}
    <link href="{% static "css/preferences.css" %}" rel="stylesheet">
{% endcompress %}
{% endblock %}
{% block content %}
    <div class="main">
        <div class="container">
            <div class="row">
                <div class="col-md-12" role="main">
                    <h2>{% trans "Script permissions settings" %}</h2>
                    <div id="permissionsEditor"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block append-body %}
    {% compress js %}
    {% include "scripts/scripts.inc.html" %}
    <script>
        $(function(){App().renderPrefs('#permissionsEditor')});
    </script>
    {% endcompress %}
{% endblock %}

server/sell-script-backend/scripts/templates/scripts/scripts.inc.html
{% load staticfiles %}
{% if not debug %}
    <script src="{% static "js/scenarist-jsdeps.min.js" %}"></script>
    <script src="{% static "js/scenarist-opt.js" %}"></script>
    <script src="{% static "js/scenarist-launcher.js" %}"></script>
{% else %}
    <script src="http://127.0.0.1:12345/target/scala-2.12/scenarist-jsdeps.js"></script>
    <script src="http://127.0.0.1:12345/target/scala-2.12/scenarist-fastopt.js"></script>
    <script src="http://127.0.0.1:12345/target/scala-2.12/scenarist-launcher.js"></script>
{% endif %}
{#http://127.0.0.1:12345/target/scala-2.11/scenarist-fastopt.js#}

server/sell-script-backend/scripts/templates/scripts/stats-summary.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block title-subject %}{% trans "stats"|capfirst %}{% endblock %}
{% block append-head %}
{% compress css %}
<link href="{% static "css/viewer.css" %}" rel="stylesheet">
{% endcompress %}
{% endblock %}

{% block main %}
    <h1>Loading script..</h1>
{% endblock %}
{% block append-body %}
    {% compress js %}
    {% include "scripts/scripts.inc.html" %}
    <script>
        $(function(){App().renderStatsAll('.main')});
    </script>
    {% endcompress %}
{% endblock %}

server/sell-script-backend/scripts/templates/scripts/viewer.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block title-subject %}{% trans "Viewer" %}{% endblock %}
{% block append-head %}
{% compress css %}
<link href="{% static "css/viewer.css" %}" rel="stylesheet">
{% endcompress %}
{% endblock %}

{% block main %}
    <h1>Loading script..</h1>
{% endblock %}
{% block append-body %}
    {% compress js %}
    <script src="{% static "js/counters.js" %}"></script>
    {% include "scripts/scripts.inc.html" %}
    <script>
        $(function(){App().renderViewer('.main')});
    </script>
    {% endcompress %}
{% endblock %}