server/sell-script-backend/backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_reset_confirm, password_change
from django.conf.urls.i18n import i18n_patterns

from django.contrib.sitemaps.views import sitemap
from django.core.urlresolvers import reverse
from django.contrib.sitemaps import Sitemap
from django.views.generic import RedirectView, TemplateView
from django.contrib.staticfiles.templatetags.staticfiles import static

from clients.views import do_login
from clients.forms import SaleScriptPasswordChangeForm
from common.views import MultilingualTemplateView, current_user


class ViewSitemap(Sitemap):
    """Reverse 'static' views for XML sitemap."""

    def items(self):
        # Return list of url names for views to include in sitemap
        return ['main', 'faq']

    def location(self, item):
        return reverse(item)

    i18n = True


sitemaps = {'views': ViewSitemap}


urlpatterns = [
    #SEO
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt'), name='robots'),

    url(r'^sitemap\.xml$', TemplateView.as_view(
        template_name='sitemap.xml'), name='sitemap'),
    #

    url(r'^admin/', admin.site.urls),
    url(r'^api/current_user$', current_user),
    url(r'^api/', include('scripts.api_urls')),
    url('', include('social.apps.django_app.urls', namespace='social'))
]

urlpatterns += i18n_patterns(
    url(r'^client/', include('clients.urls')),

    #Redefine password reset confirm
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        do_login(password_reset_confirm), name='password_reset_confirm',
        kwargs={'post_reset_redirect': 'clients:dashboard'}),  #

    #Redefine password change
    url(r'^password_change/$', password_change, name='password_change',
        kwargs={'password_change_form': SaleScriptPasswordChangeForm}),

    url(r'^', include('django.contrib.auth.urls')),

    url(r'^scripts/', include('scripts.urls')),

    url(r'^$', MultilingualTemplateView.as_view(
        template_name='main.html',
        multilang_template='main.{LANGUAGE_CODE}.html'), name="main"),

    url(r'^faq$', MultilingualTemplateView.as_view(
        template_name='faq.html',
        multilang_template='faq.{LANGUAGE_CODE}.html'), name="faq"),

    url(r'^termsofuse$', RedirectView.as_view(
        url=static('salescript_toe_ru.pdf')), name='toe'),

    url(r'^confidential$', RedirectView.as_view(
        url=static('salescript_confidential_ru.pdf')), name='confidential'),

)

server/sell-script-backend/clients/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy

from .views import (DashboardView, ProfileView, ClientRegistrationView)

app_name = 'clients'
urlpatterns = [
    url(r'^register', ClientRegistrationView.as_view(
            success_url=reverse_lazy('clients:dashboard')),
        name='register'),

    url(r'^dashboard', DashboardView.as_view(),
        name='dashboard'),

    url(r'^profile', ProfileView.as_view(),
        name='profile'),
]

server/sell-script-backend/scripts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import ExportScriptsView, ImportScriptsView

app_name = 'scripts'
urlpatterns = [
    url(r'^editor', TemplateView.as_view(template_name='scripts/editor.html'),
        name='editor'),
    url(r'^viewer', TemplateView.as_view(template_name='scripts/viewer.html'),
        name='viewer'),
    url(r'^preferences', TemplateView.as_view(template_name='scripts/preferences.html'),
        name='preferences'),
    url(r'^stats', TemplateView.as_view(template_name='scripts/stats-summary.html'),
        name='stats-all'),
    url(r'^download', ExportScriptsView.as_view(),
        name='download'),
    url(r'^migrate', ImportScriptsView.as_view(),
        name='migrate'),
]

server/sell-script-backend/clients/models.py
from django.db import transaction, IntegrityError
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser


@transaction.atomic()
def get_or_create_user_with_email(email: str) -> (AbstractUser, bool):
    """
    Fetches or creates a user with the given email address.

    The User instance with given :param email will be returned if exists.
    Otherwise, returns instance of the new created user with the username
    of email (w/o domain parm) and an optional suffix to avoid a username
    collision.

    :returns Pair of User and Created flag
    """
    user_model = get_user_model()  # type: AbstractUser
    try:
        return user_model.objects.get(email=email), False
    except user_model.DoesNotExist:
        slug = email.split('@')[0]
        try:
            with transaction.atomic():
                user = user_model.objects.create(username=slug, email=email)
        except IntegrityError:
            suffix = 1
            while True:
                try:
                    with transaction.atomic():
                        user = user_model.objects.create(
                            username='{}{}'.format(slug, suffix), email=email)
                    break
                except IntegrityError:
                    if suffix < 9999:
                        suffix += 1
                    else:
                        raise
    return user, True

server/sell-script-backend/clients/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm

User = get_user_model()


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as before, for verification."))

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if (email and User.objects.filter(email=email)
                .exists()):
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.instance.username
        if (email and User.objects.filter(email=email)
                .exclude(username=username)
                .exists()):
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email


class SaleScriptPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        user = self.user
        if not user.has_usable_password() and user.is_active:
            self.fields.pop('old_password')

server/sell-script-backend/clients/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, UpdateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model, login as auth_login
from django.http.response import HttpResponseRedirect
from django.shortcuts import resolve_url
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.conf import settings

from scripts.models import Script
from .forms import UserCreationForm, UserProfileForm

User = get_user_model()


class ClientRegistrationView(CreateView):
    """
    New user registration.
    """
    form_class = UserCreationForm
    template_name = 'clients/register.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password1'])
        login(self.request, user)
        return result


class DashboardView(LoginRequiredMixin, TemplateView):
    """
    Dashboard - main client's view.
    Shows service expiration date, tariffs, bills, etc.
    """
    template_name = 'clients/dashboard.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['scripts'] = Script.objects.allowed_to(self.request.user)
        return data


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'clients/profile.html'
    model = get_user_model()
    form_class = UserProfileForm
    success_url = reverse_lazy('clients:dashboard')

    def get_object(self, queryset=None):
        return self.request.user


def do_login(view):
    def wrapped(request, **kwargs):
        response = view(request, **kwargs)
        response_after_login = HttpResponseRedirect(
            resolve_url('clients:dashboard'))
        if (isinstance(response, HttpResponseRedirect) and
                str(response.url) == str(response_after_login.url)):
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User._default_manager.get(pk=uid)
            user.backend = settings.AUTHENTICATION_BACKENDS[0]
            auth_login(request, user)
            return response_after_login
        return response
    return wrapped

server/sell-script-backend/clients/templates/clients/dashboard.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block title-subject %}{% trans "dashboard"|capfirst %}{% endblock %}
{% block main %}
  <div class="row">
    <h2>{% trans "scenarios"|capfirst %}</h2>
    {% for script in scripts %}
      <div class="col-sm-6">
        <div class="panel panel-default scenario-breadcrumb">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a href="{% url 'scripts:viewer' %}?script={{ script.pk }}">
                {{ script.title }}
              </a>
            </h3>
          </div>
          <div class="panel-body">
            {% trans "no description"|capfirst as no_description_given %}
            <p>{% trans "description"|capfirst %}:
              {% firstof script.description no_description_given %}</p>
            <p>{% trans "author"|capfirst %}: {{ script.author }}</p>
            <p>{% trans "creation date"|capfirst %}: {{ script.created }}</p>
            <div class="btn-group btn-group-sm btn-group-justified"
                 role="group">
              <a class="btn btn-primary"
                 href="{% url 'scripts:viewer' %}?script={{ script.pk }}">
                {% trans "open"|capfirst %}
              </a>
              {% if script.has_perm_change %}
                <a class="btn btn-primary"
                   href="{% url 'scripts:editor' %}?script={{ script.pk }}">
                  {% trans "edit"|capfirst %}
                </a>
              {% endif %}
              <a class="btn btn-danger"
                 data-toggle="modal" data-target="#scriptRemoveDialog"
                 data-pk="{{ script.pk }}"
                 data-title="{{ script.title }}"
                 href="#">
                {% trans "delete"|capfirst %}
              </a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="row" style="padding-bottom: 20px">
    <div class="col-sm-12">
      <a class="btn btn-lg btn-success"
         href="{% url 'scripts:editor' %}">{% trans "Create new script with the Editor" %}</a>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <a class="btn btn-lg btn-info"
         href="{% url 'scripts:migrate' %}">{% trans "Export/Import Profile" %}</a>
    </div>
  </div>

  <div class="modal fade" tabindex="-1" role="dialog" id="scriptRemoveDialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">{% trans "Script deletion" %}</h4>
        </div>
        <div class="modal-body">
          <span id="dialogScriptTitle"></span>
          <span>{% trans " - script will be deleted. Please confirm." %}</span>
        </div>
        <div class="modal-footer">
          <button type="button" id="proceedDeletion" class="btn btn-danger">
            {% trans "Proceed" %}
          </button>
          <button type="button" class="btn btn-primary"
                  data-dismiss="modal">
            {% trans "Cancel" %}
          </button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endblock %}

{% block append-body %}
  {% compress js %}
    <script src="{% static "js/scenarist-jsdeps.min.js" %}"></script>
    <script src="{% static "js/scenarist-opt.js" %}"></script>
    <script src="{% static "js/scenarist-launcher.js" %}"></script>
  {% endcompress %}
  <script>
    $('#scriptRemoveDialog').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget);
      var scriptTitle = button.data('title'),
        scriptPk = button.data('pk');
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this);
      modal.find('#dialogScriptTitle').text(scriptTitle);
      modal.find('#proceedDeletion').on('click', function () {
        $.ajax({
          url: '/api/scripts/' + scriptPk + '/',
          method: 'DELETE',
          headers: {'X-CSRFToken': App().csrf()}
        }).done(function () {
          window.location.href = '{% url 'clients:dashboard' %}';
        });
      });
    })
  </script>
{% endblock %}

server/sell-script-backend/clients/templates/clients/profile.html
{% extends 'base.html' %}
{% load i18n bootstrap3 %}
{% block title-subject %}Client's Profile{% endblock %}
{% block main %}
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#profile" aria-controls="profile" role="tab"
                   data-toggle="tab">{% trans 'profile'|capfirst %}</a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="profile">
                <form class="col-md-8 form" action="" role="form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">{% trans 'login'|capfirst %}</label>
                        <p class="form-control">{{ user.username }}</p>
                    </div>
                    {% bootstrap_form form %}
                    <div class="form-group">
                        <label class="control-label">{% trans "registration date"|capfirst %}</label>
                        <p class="form-control">{{ user.date_joined }}</p>
                    </div>

                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            {% trans "Save" %}
                        </button>
                        <a class="btn btn-success"
                           href="{% url 'password_change' %}">
                            {% trans "Change password" %}</a>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

server/sell-script-backend/clients/templates/clients/register.html
{% extends 'base.html' %}
{% load bootstrap3 i18n %}
{% block main %}
    <div class="row">
        <div class="col-md-offset-2 col-md-9">
            <h1 class="page-header">{% trans "registration"|capfirst %}</h1>
            <form action="" role="form" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% trans "get started"|capfirst %}
                    </button>
                {% endbuttons %}
                {% url "toe" as toe_url %}
                {% url "confidential" as confidential_url %}
                <p>
                    {% blocktrans %}Please see <a href="{{ toe_url }}">Terms of Use</a> and
                        <a href="{{ confidential_url }}">Confidentiality Policy</a>.
                    By registering, you agree to the terms of these documents.{% endblocktrans %}
                </p>
            </form>
        </div>
    </div>
{% endblock %}